# Header Menu
menu:
  Home: /
  Projects: /projects/
  Blog: /archives/ # can set archive-dir in root config to custom value
    #Contact: /contact/
  About: /about/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
  linkedin: https://linkedin.com/in/thomas-stachowski-p-e/

# Miscellaneous
color_scheme: red   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
#twitter_username: computerlab_ # twitter username without the @
default_author: Anonymous

about: Cranberry Consulting Company, LLC was started in 2023 
phone: 774-404-2626 
email: info@cranberry-consulting.com 
#address_1: 123 Some Street 
#address_3: Somewhere, MA 02169
#lat: 42.337147
#long: -71.096530
